<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_Data_TC_1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a0928a8f-8cb3-430f-9d1b-97268a904258</testSuiteGuid>
   <testCaseLink>
      <guid>b2890c3d-f85c-4e8b-8eed-c18fb281218c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login_Data_TC_1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a597a834-8d9d-42ed-9be7-1efee43fd21b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a597a834-8d9d-42ed-9be7-1efee43fd21b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>7c323548-c128-47f4-8f32-dba70f608f81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a597a834-8d9d-42ed-9be7-1efee43fd21b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>6effb496-9eca-4991-969f-44dc8d268173</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
