<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Step 3_accept_tos</name>
   <tag></tag>
   <elementGuidId>8ae82ac3-2ee5-4a36-896b-7e80edcbd70e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;accept_tos&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='accept_tos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bffca36-1a99-4856-a2e0-2bf7f837c4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accept_tos</value>
      <webElementGuid>7ab0e8a4-7429-4008-816e-8106013b4efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ece1315d-4303-45e7-8486-0d1b2127f7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0f5c00e7-a61c-4182-af33-21819c95f854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept_tos&quot;)/span[1]/input[1]</value>
      <webElementGuid>1a381cad-abb4-4ef3-a40f-62970a91582c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='accept_tos']</value>
      <webElementGuid>95f4ed63-315b-4e5e-aa34-e85ccf4af3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='accept_tos']/span/input</value>
      <webElementGuid>4595b6d5-fc19-42f0-a612-138601cd43b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>40b2ec3d-ec05-492a-bdb8-ad8db025b6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'accept_tos' and @type = 'checkbox']</value>
      <webElementGuid>2369dfb8-9006-4519-9e99-6df7dbb7fabd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
